name: 12. Build macOS El Capitan

on:
  workflow_dispatch:
    inputs:
      image_format:
        description: 'Select image format: iso for virtual machines, dmg for flash to USB drive'
        required: true
        type: choice
        options:
          - 'iso'
          - 'dmg'

jobs:
  build:
    uses: ./.github/workflows/build-macos-template.yml
    with:
      macos_version: 'El Capitan'
      image_format: ${{ inputs.image_format }}
